[package]
name = "copyforward"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"
rand_chacha = "0.3"

[[bench]]
name = "bench_copyforward"
harness = false
path = "benches/bench_copyforward.rs"
